---
title: python环境配置 
description:              
categories:
 - python
 - ubuntu
 - linux
tags: 科技宅拯救世界
---

**Unix & Linux 平台安装 Python3:**

- 打开WEB浏览器访问 https://www.python.org/downloads/source/
- 选择适用于 Unix/Linux 的源码压缩包。
- 下载及解压压缩包  Python-3.x.x.tgz**，**3.x.x 为你下载的对应版本号。
- 如果你需要自定义一些选项修改 *Modules/Setup*

以 **Python3.6.1** 版本为例：

` tar -zxvf Python-3.6.1.tgz # cd Python-3.6.1 # ./configure # make && make install`

检查 Python3 是否正常可用：

`python3 -V Python 3.6.1`





**查看已安装版本**

`python2 --version`   		#查看python2安装版本

`python3 --version `  		#查看python3安装版本



**更改系统python版本**(默认python2，然而现在python2基本不怎么用了，需要手动转换为python3)

  Python3和Python2是互相不兼容，但也不能卸载python2，可以将Python的指向Python3，这样就可以默认使用python3了。

终端输入：

`python --version`

如果终端输出python2.... 。。说明系统目前python接口为python2



**将python版本指向python3**

终端输入：

`echo alias python=python3 >> ~/.bashrc`

source一下：

`source ~/.bashrc`

系统当前python版本查看：

`python --version`



## Ubuntu1604升级Python3到3.6.2

**添加并ppa仓库并更新源**

`sudo add-apt-repository ppa:jonathonf/python-3.8`

`sudo apt-get update`

***

更新源时，无法连接到ppa.launchpad.net

解决方案：

安装了本地http代理，成功解决了问题，以下是过程：
1、安装npm
`sudo apt-get install npm`
2、下载安装http代理
`npm i -g http-proxy-to-socks`
3、使用代理
`sudo apt-get -oAcquire::Http::Proxy= update`

***

再次`sudo apt-get update`即可成功更新源



**更换系统默认的软链命令Python3到新的Python3.6**

`sudo apt-get install python3.6`

`sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.5 1`

`sudo update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.6 2`

**修改系统默认命令的软链指向，切换Python3的指向**

`sudo update-alternatives --config python3`

查看python版本：

`python3 -V`

**安装python3.6的环境 **

`sudo apt-get install python3.6-dev `

**更新pip3**

`sudo apt-get install python3-pip`

`sudo pip3 install --upgrade pip`

然后发现**ctrl+alt+T打不开终端**，查阅资料后，提供以下解决方案：

按ctrl+alt+f1进入命令行模式

输入用户名、密码登录。

输入`gnome-terminal`查看出现的终端错误

错误一：No module named "apt_pkg"，解决如下

`sudo apt-get remove --purge python-apt`

`sudo apt-get install python-apt -f `

`cd /usr/lib/python3/dist-packages/`

`sudo cp apt_pkg.cpython-35m-x86_64-linux-gnu.so apt_pkg.cpython-36m-x86_64-linux-gnu.so`

错误二：ImportError: cannot import name '_gi'

cd /usr/lib/python3/dist-packages/gi/

sudo cp _gi.cpython-35m-x86_64-linux-gnu.so _gi.cpython-36m-x86_64-linux-gnu.so

sudo cp _gi_cairo.cpython-35m-x86_64-linux-gnu.so _gi_cairo.cpython-36m-x86_64-linux-gnu.so

按ctrl alt f7进入界面模式，打开终端成功










